language: php

php:
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
      - nightly

before_install:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then PHPUNIT_FLAGS="--coverage-clover clover.xml"; fi

before_script:
  - composer -n --prefer-source install

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - if [ -f clover.xml ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi
